[package]
name = "bacon"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
inquire = { version = "0.6.2", features = ["editor"] }
pager = "0.16.1"
saehrimnir = { path = "../saehrimnir" }
